// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestGoogle.Data;

namespace TestGoogle.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190904115652_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TestGoogle.Models.MobileData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("xAco");

                    b.Property<string>("xGeo");

                    b.Property<string>("yAco");

                    b.Property<string>("yGeo");

                    b.Property<string>("zAco");

                    b.HasKey("Id");

                    b.ToTable("MobileData");
                });
#pragma warning restore 612, 618
        }
    }
}
